CREATE TABLE "coach" (
  "id" int PRIMARY KEY,
  "name" varchar,
  "age" int,
  "birth_place" varchar,
  "country" varchar,
  "coaching_license" varchar,
  "avg_term" varchar,
  "actual_team" varchar,
  "img_url" varchar
);

CREATE TABLE "coach_season" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "coach_id" int,
  "season" int,
  "team_id" int,
  "matches" int,
  "wins" int,
  "draws" int,
  "losses" int,
  "points" int,
  "ppm" float,
  "placement" int
);

CREATE TABLE "stadium" (
  "id" int PRIMARY KEY,
  "name" varchar,
  "team_id" int
);

CREATE TABLE "stadium_details" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stadium_id" int,
  "capacity" int,
  "boxes" int,
  "box_seats" int,
  "built" int,
  "formerly" varchar,
  "undersoil_heating" boolean,
  "running_track" boolean,
  "surface" varchar,
  "pitch_size" varchar,
  "address" varchar,
  "image" varchar,
  "team_image" varchar,
  "tel" varchar
);

CREATE TABLE "referee" (
  "id" int PRIMARY KEY,
  "name" varchar,
  "date_of_birth" date,
  "citizenship" varchar,
  "first_competition_debut" date,
  "image" varchar
);

CREATE TABLE "referee_matches" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "referee_id" int,
  "matchday" int,
  "date" date,
  "home_team" varchar,
  "away_team" varchar,
  "result" varchar,
  "yellow_cards" int,
  "second_yellow_cards" int,
  "red_cards" int,
  "penalty_kicks" int
);

CREATE TABLE "team" (
  "id" int PRIMARY KEY,
  "official_name" varchar,
  "name" varchar,
  "address" varchar,
  "country" varchar,
  "tel" varchar,
  "website" varchar,
  "founded" date,
  "members" int,
  "stadium" varchar,
  "squad_size" int,
  "average_age" float,
  "foreigners" int,
  "national_team_players" int
);

CREATE TABLE "team_table_stats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "season" int,
  "team_id" int,
  "position" int,
  "matches" int,
  "wins" int,
  "draws" int,
  "losses" int,
  "goals" varchar,
  "goal_difference" int,
  "points" int
);

CREATE TABLE "match" (
  "id" int PRIMARY KEY,
  "score" varchar,
  "matchday" int,
  "fst_coach_id" int,
  "scnd_coach_id" int,
  "stadium_id" int,
  "stadium_attendance" int,
  "referee_id" int
);

CREATE TABLE "match_stats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "match_id" int,
  "team_id" int,
  "total_shots" int,
  "shots_off" int,
  "shots_saved" int,
  "corners" int,
  "free_kicks" int,
  "fouls" int,
  "offsides" int
);

CREATE TABLE "goals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "match_id" int,
  "team_id" int,
  "scorer_id" int,
  "shot_type" varchar,
  "minute" int,
  "assist_player_id" int
);

CREATE TABLE "substitutions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "match_id" int,
  "minute" int,
  "substituted_player_id" int,
  "substitution_player_id" int,
  "type" varchar
);

CREATE TABLE "cards" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "match_id" int,
  "team_id" int,
  "player_id" int,
  "card_type" varchar,
  "minute" int
);

CREATE TABLE "player" (
  "id" int PRIMARY KEY,
  "name" varchar(255),
  "age" int,
  "city" varchar(255),
  "country" varchar(255),
  "height" varchar(50),
  "position" varchar(50),
  "image" varchar(255)
);

CREATE TABLE "player_stats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "player_id" int,
  "matchday" int,
  "date" date,
  "first_team" varchar(255),
  "second_team" varchar(255),
  "result" varchar(10),
  "position_on_matchday" varchar(50),
  "goals" int,
  "assists" int,
  "own_goals" int,
  "yellow_cards" int,
  "second_yellow_cards" int,
  "red_yellow_cards" int,
  "substitutions_on" int,
  "substitutions_off" int,
  "minutes_played" int
);

CREATE TABLE "player_team_season" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "season" int,
  "team_id" int,
  "number" varchar,
  "name" varchar,
  "position" varchar,
  "birth" varchar,
  "height" varchar,
  "foot" varchar,
  "joined" date,
  "image" varchar
);

CREATE TABLE "top_goalscorers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "player_id" int,
  "season" int,
  "table_position" int,
  "name" varchar(100),
  "position" varchar(50),
  "age" int,
  "appearances" int,
  "assists" int,
  "penalty_kicks" int,
  "minutes_played" int,
  "minutes_per_goal" int,
  "goals_per_match" float,
  "goals" int,
  "image" varchar(255)
);

CREATE TABLE "players_of_the_year" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "player_id" int,
  "season" int,
  "year" int,
  "name" varchar,
  "position" varchar,
  "player_image_1" varchar,
  "player_image_2" varchar,
  "team_image" varchar,
  "national_image" varchar
);

ALTER TABLE "coach_season" ADD FOREIGN KEY ("coach_id") REFERENCES "coach" ("id");

ALTER TABLE "coach_season" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "stadium" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "stadium_details" ADD FOREIGN KEY ("stadium_id") REFERENCES "stadium" ("id");

ALTER TABLE "referee_matches" ADD FOREIGN KEY ("referee_id") REFERENCES "referee" ("id");

ALTER TABLE "team_table_stats" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "match" ADD FOREIGN KEY ("fst_coach_id") REFERENCES "coach" ("id");

ALTER TABLE "match" ADD FOREIGN KEY ("scnd_coach_id") REFERENCES "coach" ("id");

ALTER TABLE "match" ADD FOREIGN KEY ("stadium_id") REFERENCES "stadium" ("id");

ALTER TABLE "match" ADD FOREIGN KEY ("referee_id") REFERENCES "referee" ("id");

ALTER TABLE "match_stats" ADD FOREIGN KEY ("match_id") REFERENCES "match" ("id");

ALTER TABLE "match_stats" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "goals" ADD FOREIGN KEY ("match_id") REFERENCES "match" ("id");

ALTER TABLE "goals" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "goals" ADD FOREIGN KEY ("scorer_id") REFERENCES "player" ("id");

ALTER TABLE "goals" ADD FOREIGN KEY ("assist_player_id") REFERENCES "player" ("id");

ALTER TABLE "substitutions" ADD FOREIGN KEY ("match_id") REFERENCES "match" ("id");

ALTER TABLE "substitutions" ADD FOREIGN KEY ("substituted_player_id") REFERENCES "player" ("id");

ALTER TABLE "substitutions" ADD FOREIGN KEY ("substitution_player_id") REFERENCES "player" ("id");

ALTER TABLE "cards" ADD FOREIGN KEY ("match_id") REFERENCES "match" ("id");

ALTER TABLE "cards" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "cards" ADD FOREIGN KEY ("player_id") REFERENCES "player" ("id");

ALTER TABLE "player_stats" ADD FOREIGN KEY ("player_id") REFERENCES "player" ("id");

ALTER TABLE "player_team_season" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "top_goalscorers" ADD FOREIGN KEY ("player_id") REFERENCES "player" ("id");

ALTER TABLE "players_of_the_year" ADD FOREIGN KEY ("player_id") REFERENCES "player" ("id");
